### ISSUE TITLE
Demonstrate the value of lazy loading the ArcGIS API for JavaScript

### ISSUE THREAD

**Issue by tomwayson** [tomwayson/esri-angular-cli-example#1]
Add a route that loads quickly. Only when the user takes an action (link, tab) to view the map should they incur the penalty of loading the ArcGIS API for JavaScript.

**Comment by TheKeithStewart** [comment]
I'm assuming you would like the quick landing page to be have a little more than just a way of navigating to the mapping component.  Any issue with me adding Angular Material to handle some of the layout?

**Comment by tomwayson** [comment]
That would be awesome!

**Comment by tomwayson** [comment]
resolved in #7
