### ISSUE TITLE
More compelling map

### ISSUE THREAD

**Issue by tomwayson** [tomwayson/esri-angular-cli-example#19]
I think it'd be nifty if this repo's app did exactly the same thing as: https://github.com/tomwayson/esri-react-router-example/ so you could compare 🍎 to 🍏.

That's why I think it'd be cool to implement the map in this app the same way [I've outlined here]( https://github.com/tomwayson/esri-react-router-example/issues/8#issuecomment-263645435)

**Comment by TheKeithStewart** [comment]
@tomwayson I am considering taking this one on.  I am thinking about mapping the location of arenas and stadiums for the major sports in the US.  There could be different feature layers for each of the sports with a widget to choose which layers are being displayed.  Also there would be popup for each graphic displaying information about the stadium.

What do you think?

**Comment by TheKeithStewart** [comment]
@tomwayson I somehow managed to write my previous comment without reading your comment above it.  I'll plan on doing something along the lines of what was done on the esri-react-router-example.

**Comment by tomwayson** [comment]
@kgs916 

It'd be great if you wanted to take this on!

My preference would be to do a 🍎 to 🍏 comparison of what I end up doing in esri-react-router-example. I have a few local commits that I haven't pushed yet with it working on Living Atlas maps. I'll get those up tonight, so you can see the latest, but I'm [still figuring out what I want to do there](https://github.com/tomwayson/esri-react-router-example/issues/22#issuecomment-268351776).

That said, if you have good sports stadium data (services) and an idea of how you want to do add components like a layer list, etc, I'd be game for that too. The most important thing to me is I want to demonstrate the lazy loading. So, one idea would be, like the esri-react-router example, maybe the home route could explain the purpose of the example app and have a search form that transitions to a new `/stadiums?q=Los+Angeles` route that searches the stadiums based on name, location, or team, etc passed via query string and then lists each w/ a link that takes you to the stadium details route (i.e.  `/stadiums/42`). That route would finally load and show a map and maybe other details about that stadium (w/ id `42`).

Since you're volunteering your time, I'll leave it up to you which way you want to go as long as what ever it is makes meaningful use of the lazy loading capability that I'm trying to demonstrate with this example.

**Comment by tomwayson** [comment]
FYI - I've pushed some commits to esri-react-router that have it searching the living atlas (for now): https://tomwayson.github.io/esri-react-router-example/

**Comment by TheKeithStewart** [comment]
@tomwayson, I'm having an issue with popups within maps in the example.  I'm loading a WebMap but none of the popups in the map will display.  Instead there are just loading images that show up on the left side of the map.  The content of the popup does get into the DOM but cannot be seed on the page.

I'm having a similar issue when I add my own graphics to a feature layer and include a popuptemplate.  This really has me stumped at the moment.

I've created a branch and pushed an update to the GitHub Pages for my fork.  The branch is https://github.com/kgs916/esri-angular-cli-example/tree/compellingMap and you can see the running map at https://kgs916.github.io/esri-angular-cli-example/map.  If you have an opportunity would you mind taking a look and letting me know if anything jumps out at you that could be causing this?

**Comment by TheKeithStewart** [comment]
@tomwayson I'm still struggling with the popups on maps.  When you have a chance if you could take a look at this and let me know if you have any ideas I'd appreciate it.

**Comment by tomwayson** [comment]
Hey @kgs916 I still haven't had a chance to look at this, I've been slammed catching up since I was on vacation. I _will_ get to it, but not looking like until later next week at this point. Thank you for your patience.

I suspect that this has to do w/ the interplay btw material and esri styles (w/o having looked at your code at all). I'm pinging @jwasilgeo b/c he's dealt w/ material and Esri and maybe he has a chance to look at your code.

**Comment by TheKeithStewart** [comment]
Thanks for the update, @tomwayson!  I know how it is coming back from vacation.

@jwasilgeo, if you are able to take a look I'd appreciate it as well.  In the mean time I will take a look at any conflicts there might be between ESRI and Angular Material CSS.

**Comment by jwasilgeo** [comment]
@kgs916 can you change the Esri js and css to use the latest JSAPI v4.2?  I see a combo of v4.1 (js) and v4.0 (css).  If you poke around in the DOM, the popup-related elements are there, but the positioning is all funky and hidden behind the view (look for a `div` with `class="esri-popup esri-widget"`).  If you can update the versions, and push to gh-pages again, please let me know and I can continue to help debug.

**Comment by TheKeithStewart** [comment]
Good catch, @jwasilgeo!  That was the issue.  After loading v4.2 of the js and css the popups worked just fine.  Thanks for the help!

**Comment by jwasilgeo** [comment]
@kgs916 I'm glad to hear that solved the popups issue.  Anything else I can do to help you out with this effort?

**Comment by TheKeithStewart** [comment]
Thanks for the offer, @jwasilgeo. I've slowed down a bit on this because I've got some release deadlines on other projects that I've got to hit right now. 

I'm probably going to be picking up the pace on this task after this weekend. Im thinking to make some incremental, small pull requess just to get this moving. I'll reach out if I run into any snags.

**Comment by tomwayson** [comment]
bumped priority down after #28

**Comment by TheKeithStewart** [comment]
Thanks, @tomwayson!  I keep on trying to get back on this but the last couple months have seemed to be non stop at work.

**Comment by tomwayson** [comment]
no worries, that's why I bumped down the priority

**Comment by tomwayson** [comment]
I'm considering this done as of #28
