### ISSUE TITLE
More angular-cli way to load the ArcGIS (and font?) CSS

### ISSUE THREAD

**Issue by tomwayson** [tomwayson/esri-angular-cli-example#22]
Currently we [add a link to the CDN stylesheet in index.html](https://github.com/tomwayson/esri-angular-cli-example/blob/e72c8135dce77d465ed5b50ea5a4d24b67bb8105/src/index.html#L14). 

That works, but a more angular-cli way to do it would probably be to [add them to the `apps[0].styles` array](https://github.com/angular/angular-cli#global-library-installation).

**Comment by tomwayson** [comment]
Would also want to update the sentance under the [goal section of the README](https://github.com/tomwayson/esri-angular-cli-example/#goal) with the required steps. The preceding paragraph and the new instructions should probably become their own section called "How it works".

**Comment by jwasilgeo** [comment]
@tomwayson I have begun to look into this, and admittedly only with a half hour spent on it so far, I've had luck with `@import`s in the main styles.css, rather than adding full hrefs to the `apps[0].styles` array.  For example:

```css
@import '~@angular/material/core/theming/prebuilt/indigo-pink.css';

@import '//js.arcgis.com/4.2/esri/css/main.css';

@import '//fonts.googleapis.com/icon?family=Material+Icons';

html, body {
...
...
```

Then, these get added to the DOM:
![image](https://cloud.githubusercontent.com/assets/4933392/22525433/c190e39e-e88c-11e6-9ff2-06a1b4606bd5.png)

I'll look a bit more at the angular-cli source to see if there's a way to define links in the `angular-cli.json`.

**Comment by TheKeithStewart** [comment]
@tomwayson and @jwasilgeo, looking at the [getting started guide](https://github.com/angular/material2/blob/master/guides/getting-started.md) for the Angular Material 2 project it looks like the recommendation for adding the font icons styles is in the index.html even in an Angular CLI app.  I would assume this would go for any remote libraries that you wanted included (i.e. main.css from arcgis.com).

As for things like the theming CSS that you would be grabbing from local files in the node_modules directory using the `@import` statement like this seems appropriate.  Another reference for that can be found in the Angular Material 2 [Theming Guide](https://github.com/angular/material2/blob/master/guides/theming.md).

**Comment by jwasilgeo** [comment]
Interesting, thanks for pointing all that out, @kgs916.

How do y'all want to proceed?

**Comment by tomwayson** [comment]
Thanks guys.

`@import` statements work for me - less ✨magic✨. Main thing I care about are:
1. getting them out of index.html
1. doc'ing in the readme where to add them

**Comment by jwasilgeo** [comment]
On it.
