### ISSUE TITLE
Add instructions to README on how to add ArcGIS to a new angular-cli app

### ISSUE THREAD

**Issue by tomwayson** [tomwayson/esri-angular-cli-example#30]
#29 highlights the need for instructions that shows the minimal steps to start using the ArcGIS API in an angular-cli app rather than leaving it up to devs to reverse engineer from this increasingly complex example app. Something that starts where [the angular-cli instructions for creating a new app](https://github.com/angular/angular-cli#generating-and-serving-an-angular-project-via-a-development-server) leaves off and walks devs through these steps:
1. installing angular2-esri-loader
1. registering that service w/ the app's DI
1. create a new map route (optional?)
1. create a new component that uses the service to show a map 

I think the instructions and required code snippets could live in a gist and we'd just link to that from the README of this app.

**Comment by tomwayson** [comment]
A better idea is to help @jwasilgeo make his [gist on how to add esri libraries to angular2-webpack-starter](https://gist.github.com/jwasilgeo/00855ee002aca822e33abd8a7a031f56) more generic so it applies to angular-cli as well. Then just link to that from the README.

**Comment by jwasilgeo** [comment]
@tomwayson please take another look now, and feel free to edit the gist.
