### ISSUE TITLE
Show how to use the official type definitions for the ArcGIS API for JavaScript

### ISSUE THREAD

**Issue by tomwayson** [tomwayson/esri-angular-cli-example#4]
I'm not a TS guy, but I get the impression that [this line](https://github.com/tomwayson/angular-cli-esri/blob/master/src/app/esri-map/esri-map.component.ts#L42) should look something like:
```
this.esriLoader.require(['esri/map'], (Map: Map) => {
```

Need to include the [ArcGIS d.ts](https://github.com/Esri/jsapi-resources/tree/master/3.x/typescript) and then do something with it, right? Like add wierd `/// ref` comments to some files or something. Again - I'm not a TS guy.

**Comment by tomwayson** [comment]
See https://github.com/tomwayson/angular2-esri-loader/issues/2

**Comment by patrickarlt** [comment]
@tomwayson assign this one to me too and I can do it :)

Oh god I am the TypeScript guy now aren't I...

**Comment by tomwayson** [comment]
It's all yours (GH won't let me assign til you accept invite I guess).

@odoe you have a challenger for the TS throne

**Comment by patrickarlt** [comment]
@odoe you can have it. It's fine.

**Comment by odoe** [comment]
Welcome to the world of TS, first, let's talk about multi-inheritance constructor interfaces...

**Comment by tomwayson** [comment]
In the case of this repo, since we're using angular2-esri4-components, there is no need to declare a dev dependency on the ArcGIS types. This issue was effectively resolved in #27.

However, for others that might not be using that component library, you'll want to see https://github.com/tomwayson/angular2-esri-loader/issues/2
