### ISSUE TITLE
How to enable snapping

### ISSUE THREAD

**Issue by tomasvoj** [tomwayson/esri-angular-cli-example#42]
Hi @tomwayson, I've tried to create an app using this esri-angular-cli-example (API version 3.21). But I can't enable snapping, before draw toolbar is activated. Here is my map.service method:

```    
 enableSnapping(layers) {
  this.esriLoader.loadModules([
    'esri/SnappingManager']).then(([SnappingManager]) => {
       let layerInfos = [{
          layer: layers[0],
          snapToEdge: true,
          snapToPoint: true,
          snapToVertex: true
        }];
        let snapManager = new SnappingManager({
          alwaysSnap: true,
          layerInfos: layerInfos,
          map: this.map
        })
        this.map.enableSnapping(snapManager);
      }
    );
}
```

Any ideas please?

**Comment by tomwayson** [comment]
I've not ever done this, but I'm guessing that if you included `esri/SnappingManager` in the same call to `loadModules()` that you use to create the map (or the one that activates the drawing toolbar), you should be able to control the timing of when you call `enableSnapping`.

**Comment by tomasvoj** [comment]
Thanks, I've done it as you wrote. But I've already made a mistake in the layerInfo's layer property before. Now it works.
