### ISSUE TITLE
error during npm install

### ISSUE THREAD

**Issue by assaftenen** [tomwayson/esri-angular-cli-example#43]
[2017-11-02T12_26_00_787Z-debug.log](https://github.com/tomwayson/esri-angular-cli-example/files/1437684/2017-11-02T12_26_00_787Z-debug.log)

Im getting the next error =>
npm ERR! code EINTEGRITY
npm ERR! sha1-7znN6ierrAtQAkLWcmq5DgyEZjE= integrity checksum failed when using sha1: wanted sha1-7znN6ierrAtQAkLWcmq5DgyEZjE= but got sha1-yISc6nreDBl2Y3wLQgSAt1Hin7
I=. (245351 bytes)

attached the debug.log, cant figure it out
till now:
Clean cach
use yarn
upgrading angular material library
any help will be appriciated

**Comment by tomwayson** [comment]
Are you trying to run npm install this repo? You should *not*. See https://github.com/tomwayson/esri-angular-cli-example/blob/master/README.md#adding-the-arcgis-api-to-your-own-angular-cli-application
